auto_upload:
  video_enable: true  # 是否自动上传视频
  image_enable: true  # 是否自动上传图片
  max_upload_num: 5  # 最大并发上传数
  max_upload_size: 30  # 最大上传文件大小

  # 排除的设备
  exclude_device_models:
    - "xiaomi 24069RA21C"
